apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace-mutated.yaml

patches:
- patch: |-
    - op: remove
      path: /metadata/labels/component
  target:
    kind: Namespace
    version: v1
    group: ""

